export const LOGIN = 'ACCOUNT/LOGIN'
export const REGISTER = 'ACCOUNT/REGISTER'

export const LOGOUT = 'APP/LOGOUT'

export const GET_EXPENSE_TYPES = 'EXPENSES/GET_EXPENSE_TYPES'
export const GET_EXPENSES_BY_MONTH = 'EXPENSES/GET_EXPENSES_BY_MONTH'
export const GET_EXPENSES = 'EXPENSES/GET_EXPENSES'
export const DELETE_EXPENSE = 'EXPENSES/DELETE_EXPENSE'
export const UPDATE_EXPENSE = 'EXPENSES/UPDATE_EXPENSE'
export const CREATE_EXPENSE = 'EXPENSES/CREATE_EXPENSE'
export const GET_STATISTICS = 'EXPENSES/STATISTICS/GET_STATISTICS'
export const UPDATE_SELECTED_MONTHS_DATE = 'EXPENSES/UPDATE_SELECTED_MONTHS_DATE'